document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-cn\'>");
document.writeln("<head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0\">");
document.writeln("	<title>熊猫资源-账号密码</title>");
document.writeln("");
document.writeln("	<link rel=\'stylesheet\' href=\'https://cdn.bootcss.com/normalize/5.0.0/normalize.min.css\'>");
document.writeln("	<script src=\"https://cdn.bootcss.com/jquery/3.3.0/jquery.min.js\"></script>");
document.writeln("	<style>");
document.writeln("	html,body {height: 100%;margin: 0;padding: 0;}body {font-family: \'lucida grande\', \'lucida sans unicode\', lucida, helvetica, \'Hiragino Sans GB\', \'Microsoft YaHei\', \'WenQuanYi Micro Hei\', sans-serif;align-items: center;display: flex;}a{text-decoration:none;}#container {max-width: 400px;flex-basis: 100%;margin: 0 auto;background: #FFF;border-radius: 10px;box-shadow: 0 0 30px rgba(0, 0, 0, 0.3);-webkit-box-shadow: 0 0 30px rgba(0, 0, 0, 0.3);overflow: hidden;}#container #hero-img {width: 100%;height: 200px;background: #007bff;}#container #profile-img {width: 160px;height: 160px;margin: -80px auto 0 auto;}#container #profile-img img {width: 100%;background: #FFF;border-radius: 50%;}#container #content {text-align: center;width: 320px;margin: 0 auto;padding: 0 0 50px 0;}#container #content h1 {font-size: 29px;font-weight: 500;margin: 30px 0 0 0;}#container #content p {font-size: 18px;font-weight: 400;line-height: 1.4;color: #666;margin: 15px 0 40px 0;}#container #content a {color: #CCC;font-size: 14px;margin: 0 10px;transition: color .3s ease-in-out;-webkit-transition: color .3s ease-in-out;line-height: 40px;}#container #content a:hover {color: #007bff;}.btn{background: none repeat scroll 0 0 #1BA1E2; border: 0 none; border-radius: 2px; color: #FFFFFF !important; cursor: pointer; font-family: \"Open Sans\",\"Hiragino Sans GB\",\"Microsoft YaHei\",\"WenQuanYi Micro Hei\",Arial,Verdana,Tahoma,sans-serif; font-size: 14px;  padding: 6px 10%;}.btn:hover,.yanshibtn:hover{background: none repeat scroll 0 0 #9B59B6; border: 0 none; border-radius: 2px; color: #FFFFFF!important; cursor: pointer; font-family: \"Open Sans\",\"Hiragino Sans GB\",\"Microsoft YaHei\",\"WenQuanYi Micro Hei\",Arial,Verdana,Tahoma,sans-serif; font-size: 14px; padding: 8px 10%;}");
document.writeln("	.imgType{display: none;}");
document.writeln("	#images img{width: 100%}");
document.writeln("	#imgurl input{width: 100%}");
document.writeln("	#imgurl,#progress{display: none;}");
document.writeln("");
document.writeln("	@-webkit-keyframes rotation{");
document.writeln("		from {-webkit-transform: rotate(0deg);}");
document.writeln("		to {-webkit-transform: rotate(360deg);}");
document.writeln("	}");
document.writeln("");
document.writeln("	.Rotation{");
document.writeln("		-webkit-transform: rotate(360deg);");
document.writeln("		animation: rotation 3s linear infinite;");
document.writeln("		-moz-animation: rotation 3s linear infinite;");
document.writeln("		-webkit-animation: rotation 3s linear infinite;");
document.writeln("		-o-animation: rotation 3s linear infinite;");
document.writeln("	}");
document.writeln("");
document.writeln("	.img{border-radius: 250px;}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("	<div id=\'container\'>");
document.writeln("		<div id=\'hero-img\'>");
document.writeln("		</div>");
document.writeln("		<div id=\'profile-img\'>");
document.writeln("			<img src=\'https://ae01.alicdn.com/kf/Hb2315cf430f54f45beddd68e6c0b24d6s.png\' id=\"imgLoading\" class=\"Rotation img\" title=\"显示与隐藏\"/>");
document.writeln("		</div>");
document.writeln("<script>");
document.writeln("   function check(){");
document.writeln("      var name=document.getElementById(\"name\").value;");
document.writeln("   var pass=document.getElementById(\"pass\").value;");
document.writeln("   if(name==\"网球\" && pass==\"xm08.cn\"){");
document.writeln("   alert(\"密码正确 欢迎造访 记得常来\");");
document.writeln("   window.document.f.action=\"2019.10.13.html\";");
document.writeln("   window.document.f.submit();");
document.writeln("   }else{");
document.writeln("   alert(\"小样儿 没账号密码也敢乱点 加熊猫要密码\");");
document.writeln("   ");
document.writeln("   }");
document.writeln("   ");
document.writeln("   }");
document.writeln("</script>");
document.writeln("");
document.writeln("<form name=\"f\" action=\"\">");
document.writeln("<center>账号:<INPUT TYPE=\"text\" NAME=\"\" id=\"name\"><br></center>");
document.writeln("<center>密码:<INPUT TYPE=\"password\" NAME=\"\" id=\"pass\"><br></center>");
document.writeln("<center><INPUT TYPE=\"button\" value=\"确认\" onclick=\"check()\"></center>");
document.writeln("</form>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</body>");
document.writeln("</script>");
document.writeln("</html>");